import type { Metadata } from 'next'
import { Manjari as ABeeZee } from 'next/font/google'
import StyledComponentsRegistry from '@/lib/registry'
import { GlobalCss } from './styles'

const noto = ABeeZee({
  subsets: ['latin'],
  weight: ['100', '400', '700']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={noto.className}>
        <StyledComponentsRegistry>
          <GlobalCss />
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
